version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password@123
      POSTGRES_DB: ecom
    networks:
      - ecom
    volumes:
      - dev-db-data:/var/lib/postgresql/data
  dev-cache:
    image: redis:6.0.9
    ports:
      - 6379:6379
    networks:
      - ecom

  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: test_postgres
      POSTGRES_PASSWORD: Password@123
      POSTGRES_DB: ecom
    networks:
      - ecom
networks:
  ecom:
volumes:
  dev-db-data:
